### ISSUE TITLE
404: Not Found

### ISSUE THREAD

**Issue by dw9694** [wmnnd/nginx-certbot#53]
```
$ curl -s https://raw.githubusercontent.com/certbot/certbot/master/certbot-nginx/certbot_nginx/tls_configs/options-ssl-nginx.conf                                                              
404: Not Found
```

_Originally posted by @dw9694 in https://github.com/wmnnd/nginx-certbot/pull/39#issuecomment-558463376_

**Comment by abhimediratta** [comment]
```
curl -s https://raw.githubusercontent.com/certbot/certbot/https://raw.githubusercontent.com/certbot/certbot/master/certbot-nginx/certbot_nginx/_internal/tls_configs/options-ssl-nginx.conf > "$data_path/conf/options-ssl-nginx.conf"
  curl -s https://raw.githubusercontent.com/certbot/certbot/master/certbot/certbot/ssl-dhparams.pem > "$data_path/conf/ssl-dhparams.pem"```

^^^with updated URLs

**Comment by abhimediratta** [comment]
```
curl -s https://raw.githubusercontent.com/certbot/certbot/master/certbot-nginx/certbot_nginx/_internal/tls_configs/options-ssl-nginx.conf > "$data_path/conf/options-ssl-nginx.conf"
curl -s https://raw.githubusercontent.com/certbot/certbot/master/certbot/certbot/ssl-dhparams.pem > "$data_path/conf/ssl-dhparams.pem"
```

With updated URLs^

**Comment by dw9694** [comment]
Developers certbot write:

> Make the contents of the nginx plugin private `https://github.com/certbot/certbot/pull/7589`

**Comment by VivianSolide** [comment]
Even if I replace these urls, I'm getting this error:
```
[emerg] 1#1: unexpected end of file, expecting ";" or "}" in /etc/letsencrypt/options-ssl-nginx.conf:2
```
I double checked the [file](https://raw.githubusercontent.com/certbot/certbot/master/certbot-nginx/certbot_nginx/_internal/tls_configs/options-ssl-nginx.conf) and all the semi colons are included.

Do I need to change my app.conf and docker-compose.yml aswell?

**Comment by wmnnd** [comment]
Thanks everyone for reporting this, the URLs have been fixed in Merge Request #55 .

**Comment by markhorrocks** [comment]
This is not fixed, the contents of options-ssl-nginx.conf is 404.
